/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require('express');
const bodyParser = require('body-parser');
const jwt = require("jsonwebtoken");
const app = express();

app.use(bodyParser.json());

let TODOS = [];

// ACCESSING ALL TODOS.
app.get("/todos", (req, res) => {
    res.json({
        TODOS
    })
})

// ACCESSING A TODO WITH SPECIFIC ID.
app.get('/todos/:id', (req, res) => {
    const id = parseInt(req.params.id);

    const existingTodo = TODOS.find((e) => e.id === id);
    if (!existingTodo) {
        res.status(404).json({
            message: "Todo not found"
        })
        return;
    }
    res.json({
        id: existingTodo.id,
        title: existingTodo.title,
        description: existingTodo.description
    })
})

// CREATING A TODO
app.post("/todos", (req, res) => {
    const title = req.body.title;
    const description = req.body.description;

    const existingTodo = TODOS.find((e) => e.title === title && e.description === description);

    if (existingTodo) {
        res.status(403).json({
            message: "Your todo already exist"
        })
        return;
    }
    function randomId(todos) {
        let id;
        do {
            id = Math.floor(Math.random() * 10) + 1;
        } while (TODOS.some(t => t.id === id))
        return id;
    }
    const newId = parseInt(randomId(TODOS));

    TODOS.push({
        id: newId,
        title,
        description
    })
    console.log(TODOS);
    res.json({
        message: "TODO created"
    })
    return;

})

// UPDATING A TODO WITH SPECIFIC ID
app.put("/todos/:id", (req, res) => {
    const id = parseInt(req.params.id);
    const title = req.body.title;
    const description = req.body.description;

    const existingTodo = TODOS.find(e => e.id === id);
    if (existingTodo) {
        existingTodo.title = title;
        existingTodo.description = description;

        res.json({
            id: existingTodo.id,
            title: existingTodo.title,
            description: existingTodo.description,
            message: "Todo Updated"
        })
        return;
    } else {
        res.status(404).json({
            message: "You don't have a todo with this id"
        })
        return;
    }
})

// DELETING TODO WITH SPECIFIC ID.
app.delete("/todos/:id", (req, res) => {
    const id = parseInt(req.params.id);

    const existingTodo = TODOS.find(e => e.id === id);
    
    if(existingTodo){
        TODOS = TODOS.filter(e => e.id !== id);
        res.json({
            TODOS, 
            message: "Todo Deleted"
        })
    } else {
        res.status(404).json({
            message: "Todo not found"
        })
    }

})
module.exports =  app 